getway:
  zuul:
    routes:
      pms:
        path: /pms/**
        serviceId: pms
      auth:
        path: /auth/**
        serviceId: auth
  registry:
    address: http://bldz-service-center-01:8662/eureka/,http://bldz-service-center:8661/eureka/
  application:
    name: getway
  ctl:
    server:
      address: localhost
