pms:
  foo: dev-foo
  am:
    ok: yes
  application:
    server:
      port: 9901
    name: pms
  registry:
    address: http://bldz-service-center-01:8662/eureka/,http://bldz-service-center:8661/eureka/
  rabbit:
    host: 192.168.98.181
    port: 5672
    username: guest
    password: guest
  config:
    label: dev
    profile: dev
    discovery:
      enabled: true
      serviceId: bldz-config-center
  git:
    uri: https://github.com/cytzrs/bldz-config
    searchPaths: configs
    username:
    password:
  ctl:
    server:
      address: localhost
  
